### ISSUE TITLE
Error when importing the library

### ISSUE THREAD

**Issue by triebelf** [giannitedesco/minotaur#6]
Hi,
I was trying to use this library and cannot even import it, fails like this:
```
    from minotaur import Inotify, Mask
  File "/home/ftr8fe/.local/lib/python3.8/site-packages/minotaur/__init__.py", line 16, in <module>
    from ._base import Inotify, InotifyBase
  File "/home/ftr8fe/.local/lib/python3.8/site-packages/minotaur/_base.py", line 18, in <module>
    class InotifyBase:
  File "/home/ftr8fe/.local/lib/python3.8/site-packages/minotaur/_base.py", line 34, in InotifyBase
    _waitq: Deque[asyncio.Future[None]]
TypeError: 'type' object is not subscriptable
```

In order to support Python 3.8 and 3.10, would it make sense to put this at the top of _base.py?
`from __future__ import annotations`

**Comment by giannitedesco** [comment]
Yes, it would, nice one! :)

**Comment by giannitedesco** [comment]
Although it's only needed for python3.8 afaict, python3.9 and python3.10 are fine with these new style annotations. @triebelf does the new 0.2.0 release fix it?

**Comment by triebelf** [comment]
Yes, thank you, now it works with Python 3.8!

**Comment by giannitedesco** [comment]
Thanks for the report!
